### ISSUE TITLE
Error with token

### ISSUE THREAD

**Issue by renatoaraujo** [expertcoder/SwiftmailerSendGridBundle#17]
Hello, 

I am trying to set a Symfony 4.1 using PHP 7.2 to send emails but I am having an error:

[2018-08-17 10:17:50] app.ERROR: 401: {"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]} [] []

There is no exception being trowed but the emails are not sent and I get this error on the log file.

I could see in Travis CI that the building is being successful (not for PHP 7.2) but if you open the logs you will see the same message.

I already tried to do a cURL with the same token and it's working, so I believe the problem is with this Bundle.

Any workaround or fix preview for this!?

Cheers!

**Comment by moux2003** [comment]
The error is supposed to exists in Travis because we don't provide any api key for automated tests.

I may have an idea, @renatoaraujo can you check your `expert_coder_swiftmailer_send_grid.yaml` file and check if there is an extra underscore ('_') character  at the end of **api_key**  line ?

Seems like the recipe had a typo (https://github.com/symfony/recipes-contrib/pull/454)

**Comment by renatoaraujo** [comment]
Yes! It was exactly this! Now it's working.

So, another question that I have now that I took some time on the code.
The Exception that is raised in this example shouldn't be thrown instead of just logging and returning 0? Just asking because I still can do an "if" instead of try/catch.

Many thanks for your feedback.

Cheers!

**Comment by moux2003** [comment]
As you can see here https://github.com/expertcoder/SwiftmailerSendGridBundle/blob/0880f2a71ed72298c4b0f7d8ed0b01a03ad7bf90/src/Services/SendGridTransport.php#L184 this was an original choice. 
I've not planned to throw the error because it could break other people code, maybe for 3.x version some day.
