### ISSUE TITLE
Please add more documentation

### ISSUE THREAD

**Issue by tacman** [expertcoder/SwiftmailerSendGridBundle#18]
I've installed the bundle (Symfony4, Flex), looks very helpful.

Can you add some documentation for how to do some simple things, like getting the list of bounced emails, or sending a message through SwifterMailer+SendGrid using the bundle?

I'm not all that familiar with either SwiftMailer or SendGrid, but I'll be able to figure out how to use those components once I understand better how to access those services through this bundle.  In particular, do I need a Guzzle/SendGridClient?  I'm porting a Symfony2 application that used that, and am not sure how to use this bundle to access the SendGrid API.

**Comment by expertcoder** [comment]
If you want to view information about bounced emails etc, I am sure there is a SendGrid web console where you could view this kind of information. If you wanted to access bounced email or other information pragmatically (eg via your PHP code), I believe this PHP Library could aid with this https://github.com/sendgrid/sendgrid-php

I'm not an active user or contributor to this bundle at the moment, and not sure how clear the documentation is. Perhaps an active contributor might want to put a simple example there?

@tacman Unfortunately there are sometimes bundles/libraries out there that require a bit of intuition or experimentation to use as no one had had the chance to write concise documentation.

Good luck.

**Comment by moux2003** [comment]
@tacman This bundle only aim to easily use SendGrid as a transport for Swiftmailer. Any advanced features are (should) be described in https://github.com/sendgrid/sendgrid-php as @expertcoder said.

Once configured if you need to send simple email it's all about SwiftMailer, so please refer to this page https://symfony.com/doc/current/email.html (and just ommit the suggested configuration part because you should already have done it when installed).

Also remember that there is a PR (https://github.com/symfony/recipes-contrib/pull/454) pending that solve an issue (#14) if you used the recipe.
